# Generated by Django 4.2.5 on 2024-02-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_alter_visit_options_visit_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='past',
            field=models.BooleanField(default=False),
        ),
    ]
