# Generated by Django 4.2.5 on 2024-02-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_visit_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='available',
        ),
    ]
